### ISSUE TITLE
Impossible to easily connect to the cluster with Lens IDE

### ISSUE THREAD

**Issue by zadigus** [jelastic-jps/kubernetes#42]
Hi,

Some time ago, it was possible to easily connect to the deployed k8s cluster with [Lens IDE](https://k8slens.dev/). That tool is very handy to develop stuff on k8s. Here's the thing: if I follow [these instructions](https://www.virtuozzo.com/application-platform-docs/kubernetes-cluster-access/), then I can happily interact with the cluster by means of `kubectl` cli. That's a good start. However, I cannot connect to the cluster through Lens. It says 
```
Authentication proxy started
Refreshing connection status ...
Invalid credentials
```
I guess that Lens does not support user authentication with the token. Instead of following [these instructions](https://www.virtuozzo.com/application-platform-docs/kubernetes-cluster-access/), I did the following:

1. install the OpenVPN Access Server from the Jelastic Marketplace
2. install OpenVPN client on my computer
3. connect my VPN client to my VPN server
4. in my k8s cluster, connect to my master node and display the `/root/.kube/config` file
5. take over the remote kube config and copy / paste it to my local kube config
6. replace the `k8sm.env-8930174839.hidora.com` hostname with the k8sm node's ip address

This amounts to take the configuration obtained through [these instructions](https://www.virtuozzo.com/application-platform-docs/kubernetes-cluster-access/) and

* replace section
```
- cluster:
    server: https://env-9878152.jelastic.com/api
  name: jelastic-test
```
with
```
- cluster:
    certificate-authority-data: <data from remote cluster>
    server: https://<private-k8sm-node-ip>:6443
  name: jelastic-test
```
* replace section
```
- name: jelastic-test
  user:
    token: <user-access-token>
```
with
```
- name: jelastic-test
  user:
    client-certificate-data: <client-certificate-data>
    client-key-data: <client-key-data>
```

With that in place, I can happily connect to the cluster with Lens. Is there a way to achieve that without VPN client? With Azure, this step is made very easy with their cli. You get the "credentials" with the azure cli and your kube config is updated with exactly the above working dataset (cluster certificate-authority-data, user client-certificate-data and user client-key-data). Would something like that be also possible on Jelastic?
